# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read text file `filepath` in chunks of `chunk_size` lines and pass each
#' chunk to a user-provided `handler` function.
#'
#' @param filepath Path to the file to read
#' @param handler User-provided handler function to which chunks will be passed
#' @param chunk_size number of lines to read in as one chunk (defaults to 100000)
#' @param repeat_header Append header line(s) to beginning of each chunk
#'     (defaults to TRUE)
#' @param header_rows number of lines at the beginning of file to consider as header
#' @param skip number of lines at the beginning of the file to skip (defaults to 0)
#' @param max_rows If not `NULL`, only read the first `max_rows` lines of data
#'
#' @useDynLib chunkwise, .registration = TRUE
#' @importFrom Rcpp loadModule
#'
#' @export
read_chunkwise <- function(filepath, handler, chunk_size = 100000L, repeat_header = TRUE, header_rows = 1L, skip = 0L, max_rows = NULL) {
    invisible(.Call(`_chunkwise_read_chunkwise`, filepath, handler, chunk_size, repeat_header, header_rows, skip, max_rows))
}

